name = "techteresa"
account_id = "bc6864ad5e6ce926a800038cdd7785eb"
workers_dev = false
compatibility_date = "2025-10-02"

[build]
command = "hugo"

[site]
bucket = "public"              # Hugo output folder
entry-point = "workers-site"   # required for Pages
pages_build_output_dir = "public"
